FROM ubuntu:22.04 AS build


RUN sed -i 's/archive.ubuntu.com/mirror.yandex.ru/g' /etc/apt/sources.list && \
    sed -i 's/security.ubuntu.com/mirror.yandex.ru/g' /etc/apt/sources.list

RUN apt-get update && apt-get install -y \
    build-essential cmake git libpq-dev libssl-dev zlib1g-dev \
    nlohmann-json3-dev libcurl4-openssl-dev ca-certificates

WORKDIR /app


RUN git clone --depth 1 --branch 1.3.0 https://github.com/oatpp/oatpp.git && \
    cd oatpp && mkdir build && cd build && \
    cmake -DOATPP_BUILD_TESTS=OFF -DOATPP_INSTALL_VERSIONED=OFF .. && \
    make -j$(nproc) install


RUN git clone --depth 1 --branch 1.3.0 https://github.com/oatpp/oatpp-postgresql.git && \
    cd oatpp-postgresql && mkdir build && cd build && \
    cmake -DOATPP_BUILD_TESTS=OFF -DOATPP_INSTALL_VERSIONED=OFF .. && \
    make -j$(nproc) install


RUN git clone https://github.com/Thalhammer/jwt-cpp.git && \
    cd jwt-cpp && mkdir build && cd build && \
    cmake -DJWT_CPP_BUILD_EXAMPLES=OFF -DJWT_CPP_BUILD_TESTS=OFF .. && \
    make install


COPY . .


RUN mkdir build && cd build && cmake .. && make -j$(nproc)

WORKDIR /app/build
CMD ["./VoidCoreServer"]