FROM node:20 AS build


RUN sed -i 's/deb.debian.org/mirror.yandex.ru/g' /etc/apt/sources.list.d/debian.sources || \
    sed -i 's/deb.debian.org/mirror.yandex.ru/g' /etc/apt/sources.list

WORKDIR /app
COPY package*.json yarn.lock* ./


RUN yarn install --frozen-lockfile || yarn install
COPY . .


RUN ./node_modules/.bin/tsc -b && ./node_modules/.bin/vite build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]